---
title: "Prova Riassuntiva"
author: "Lorenzo Negro"
date: "28 aprile 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list=ls())
library(devtools)
setwd("C:/Users/user1/Desktop/UNIVERSITA'/TESI/BiocNeighbors")
load_all()
setwd("C:/Users/user1/Desktop/UNIVERSITA'/TESI/clusterExperiment")
load_all()
library(scran)
setwd("C:/Users/user1/Desktop/UNIVERSITA'/TESI/ProveTesi")
library(mclust)
library(igraph)

#Per usare adjuster rand index devo dire ogni oss a che cluster appartiene

load("simCount_ext.RDAta")
load("simData_ext.RData")
load("trueCluster_ext.RData")

####Analisi####
prop=seq(0,1,by=0.1)
cl=clusterMany(simData,k=2:15,clusterFunction="kmeans")@clusterMatrix
nclust1=st1=idx1=rep(NA,length(prop))
for(i in 1:length(prop))
{
  #MC1: makeConsensus classico con proportion da 0 a 1
  mc1=makeConsensus(cl,proportion=prop[i])
  nclust1[i]=length(table(mc1$clustering))
  st1[i]=system.time(makeConsensus(cl,proportion=prop[i]))[[3]]
  idx1[i]=adjustedRandIndex(trueCluster,mc1$clustering)
}
nclust1
st1
idx1

kclust=c(1,3,5,8,10,15,20,50,100,250,500)
nclust2=st2=idx2=rep(NA,length(kclust))
for(i in 1:length(kclust))
{
  #MC2: makeConsensus nuovo kclust diversi algoritmo walktrap
  mc2=makeConsensus2(cl, k=kclust[i], algorithm="cluster_walktrap")
  nclust2[i]=length(table(mc2$clustering))
  st2[i]=system.time(makeConsensus2(cl, k=kclust[i], algorithm="cluster_walktrap"))[[3]]
  idx2[i]=adjustedRandIndex(trueCluster,mc2$clustering)
}

nclust2
idx2
st2

nclust3=st3=idx3=rep(NA,length(kclust))
for(i in 1:length(kclust))
{
  #MC3: makeConsensus nuovo kclust diversi algoritmo walktrap
  mc3=makeConsensus2(cl, k=kclust[i], algorithm="cluster_louvain")
  nclust3[i]=length(table(mc3$clustering))
  st3[i]=system.time(makeConsensus2(cl, k=kclust[i], algorithm="cluster_louvain"))[[3]]
  idx3[i]=adjustedRandIndex(trueCluster,mc3$clustering)
}
nclust3
st3
idx3

par(mfrow=c(1,3))
plot(nclust1,type="l")
plot(st1,type="l")
plot(idx1,type="l")

plot(nclust2,type="l")
plot(st2,type="l")
plot(idx2,type="l")

plot(nclust3,type="l")
plot(st3,type="l")
plot(idx3,type="l")

#confronto 
par(mfrow=c(1,2))
plot(nclust1,col=1,type="l",xlab="proprtion",xaxt="n",main="makeConsensus")
axis(1, at=1:length(kclust), labels=prop)
plot(nclust2,col=2,type="l",xlab="k",xaxt="n",main="makeConsensus2")
axis(1, at=1:length(kclust), labels=kclust)
points(nclust3,col=3,type="l")
legend("topright",legend=c("walktrap","louvain"),col=c("red","green"),lty=1,cex=0.8)

par(mfrow=c(1,2))
plot(idx1,col=1,type="l",xlab="proprtion",xaxt="n",main="makeConsensus")
axis(1, at=1:length(kclust), labels=prop)
plot(idx2,col=2,type="l",xlab="k",xaxt="n",main="makeConsensus2")
axis(1, at=1:length(kclust), labels=kclust)
points(idx3,col=3,type="l")
legend("topright",legend=c("walktrap","louvain"),col=c("red","green"),lty=1,cex=0.8)

par(mfrow=c(1,2))
plot(st1,col=1,type="l",xlab="proprtion",xaxt="n",main="makeConsensus")
axis(1, at=1:length(kclust), labels=prop)
plot(st2,col=2,type="l",xlab="k",xaxt="n",main="makeConsensus2")
axis(1, at=1:length(kclust), labels=kclust)
points(st3,col=3,type="l")
legend("topright",legend=c("walktrap","louvain"),col=c("red","green"),lty=1,cex=0.8)

```
